<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>RadioMod.Server</AssemblyName>
    <Version>1.0.2</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>E:\Games\EFT410\SPT_Runtime\SPTarkov.Server.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.DI">
      <HintPath>E:\Games\EFT410\SPT_Runtime\SPTarkov.DI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Common">
      <HintPath>E:\Games\EFT410\SPT_Runtime\SPTarkov.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>E:\Games\EFT410\SPT_Runtime\SemanticVersioning.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Spectre.Console">
      <HintPath>E:\Games\EFT410\SPT_Runtime\Spectre.Console.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Spectre.Console.Ansi">
      <HintPath>E:\Games\EFT410\SPT_Runtime\Spectre.Console.Ansi.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
